sudo: required
language: c
os:
  - linux
compiler:
  - gcc
addons:
  apt:
    packages:
    - cmake

before_install:
  - sudo apt-get install libevent-dev
  - sudo apt-get install libssl-dev

script:
  - cmake .
  - make .